# Generated by Django 2.0.3 on 2020-07-06 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletDetails',
            fields=[
                ('wallet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_amount', models.FloatField(default=0, null=True)),
                ('convert_from', models.CharField(max_length=5)),
                ('currency_to', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(choices=[('netbanking', 'Bank'), ('card', 'Ms')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('_id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
