# Generated by Django 2.0.3 on 2020-07-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurrencyXchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletdetails',
            name='currency_type',
            field=models.CharField(default=11, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='walletdetails',
            name='payment_mode',
            field=models.CharField(choices=[('netbanking', 'netbanking'), ('card', 'card')], max_length=50),
        ),
    ]
