# Generated by Django 2.0.3 on 2020-07-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurrencyXchange', '0002_auto_20200706_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletdetails',
            name='convert_from',
        ),
        migrations.AddField(
            model_name='walletdetails',
            name='file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='walletdetails',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('AUD', 'AUD'), ('EUR', 'EUR')], max_length=3),
        ),
    ]
